shell1: shell1.c ligne_commande.c ligne_commande.h
	gcc -Wall -Werror -o shell1 shell1.c ligne_commande.c

shell2: shell2.c ligne_commande.c ligne_commande.h
	gcc -Wall -Werror -o shell2 shell2.c ligne_commande.c

clean:
	rm -f shell2 shell2
